# Generated by Django 4.1.6 on 2023-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_genre_alter_sample_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='samplepack',
        ),
        migrations.AddField(
            model_name='sample',
            name='file_src',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
