# Generated by Django 4.1.6 on 2023-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_samplepack_sample_sample_pack_alter_genre_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='oleg',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
