# Generated by Django 4.1.6 on 2023-03-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_label_sample_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepack',
            name='label',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.label'),
        ),
    ]
