# Generated by Django 4.1.6 on 2023-03-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_samplepack_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='store.label'),
        ),
    ]
