# Generated by Django 4.1.6 on 2023-03-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_sample_label_alter_sample_sample_pack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplePack',
            new_name='Pack',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='sample_pack',
            new_name='pack',
        ),
    ]
