# Generated by Django 4.1.6 on 2023-03-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_samplepack_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='genre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.genre'),
        ),
    ]
