# Generated by Django 4.1.6 on 2023-03-23 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_userrelationsample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelationSample',
            new_name='UserSampleRelation',
        ),
    ]
