# Generated by Django 4.1.6 on 2023-03-23 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_rename_userrelationsample_usersamplerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='users',
            field=models.ManyToManyField(through='store.UserSampleRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
