# Generated by Django 4.1.6 on 2023-03-23 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_sample_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='users',
            field=models.ManyToManyField(related_name='Suplex', through='store.UserSampleRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
