# Generated by Django 4.1.6 on 2023-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_usersamplerelation_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='fav',
            field=models.ManyToManyField(related_name='sup', to='store.relation'),
        ),
    ]
