# Generated by Django 4.1.6 on 2023-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_sample_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='fav',
        ),
    ]
