# Generated by Django 4.1.6 on 2023-03-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_sample_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='users',
        ),
        migrations.AlterField(
            model_name='relation',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='triton', to='store.sample'),
        ),
    ]
