# Generated by Django 4.1.6 on 2023-03-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_sample_users_alter_relation_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rels', to='store.sample'),
        ),
    ]
