# Generated by Django 4.1.6 on 2023-03-26 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_alter_relation_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='buy',
            field=models.ManyToManyField(related_name='bob', to=settings.AUTH_USER_MODEL),
        ),
    ]
