# Generated by Django 4.1.6 on 2023-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_sample_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='buy',
        ),
    ]
