# Generated by Django 4.1.6 on 2023-04-05 10:59

import base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_sample_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file_src',
            field=models.FileField(null=True, upload_to=base.services.get_path_upload_sample),
        ),
    ]
