# Generated by Django 4.1.6 on 2023-04-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_title_pack_name_rename_title_sample_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='cover_src',
            new_name='cover',
        ),
    ]
