# Generated by Django 4.1.6 on 2023-04-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_pack_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='title',
            new_name='name',
        ),
    ]
