# Generated by Django 4.1.6 on 2023-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_title_genre_name_rename_title_label_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='file_src',
            new_name='file',
        ),
        migrations.AddField(
            model_name='sample',
            name='bpm',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
