# Generated by Django 4.1.6 on 2023-04-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_file_src_sample_file_sample_bpm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='bpm',
            new_name='tempo',
        ),
    ]
