# Generated by Django 4.1.6 on 2023-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_bpm_sample_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='type',
            field=models.CharField(choices=[(1, 'One Shot'), (2, 'Loop')], default=None, max_length=10, null=True),
        ),
    ]
