# Generated by Django 4.1.6 on 2023-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(choices=[('One Shot', 'One Shot'), ('loop', 'Loop')], default=None, max_length=10, null=True),
        ),
    ]
