# Generated by Django 4.1.6 on 2023-04-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='pack',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='store.pack'),
        ),
    ]
