# Generated by Django 4.1.6 on 2023-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_sample_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
