# Generated by Django 4.1.6 on 2023-04-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_instrument_sample_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='instrument',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.instrument'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tempo',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
