# Generated by Django 4.1.6 on 2023-04-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_sample_instrument_alter_sample_tempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='fav',
            new_name='isFavorite',
        ),
        migrations.AddField(
            model_name='relation',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
